# Site settings
author: Hyeoncheol Jung
title: First day
header-img: img/home-bg.png
email: joe.hyeoncheol.jung@gmail.com
copyright_name: Hyeoncheol Jung
description: > # this means to ignore newlines until "baseurl:"
  First
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hjung1018

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
